server:
  port: 8083

spring:
  application:
    name: payment-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
  datasource:
    url: jdbc:postgresql://localhost:5435/payment_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
